name: pi2
version: 16.04-0.17
summary: Raspberry Pi 2 support package
description: |
 Support files for booting Raspberry Pi
type: gadget
architectures:
  - armhf
confinement: strict
grade: stable
parts:
    prebuilt:
        plugin: dump
        source: prebuilt
